### Generated by Winemaker 0.8.4
###
### Invocation command line was
### /usr/local/bin/winemaker --wine32 .


SRCDIR                = .
SUBDIRS               =
DLLS                  =
LIBS                  =
EXES                  = winelib_test_tray.exe



### Common settings

CEXTRA                = -mno-cygwin \
			-m32
CXXEXTRA              = -m32
RCEXTRA               =
DEFINES               =
INCLUDE_PATH          =
DLL_PATH              =
DLL_IMPORTS           =
LIBRARY_PATH          =
LIBRARIES             =


### winelib_test_tray.exe sources and settings

winelib_test_tray_exe_MODULE= winelib_test_tray.exe
winelib_test_tray_exe_C_SRCS= test_tray.c
winelib_test_tray_exe_CXX_SRCS=
winelib_test_tray_exe_RC_SRCS=
winelib_test_tray_exe_LDFLAGS= -mwindows \
			-mno-cygwin \
			-m32
winelib_test_tray_exe_ARFLAGS=
winelib_test_tray_exe_DLL_PATH=
winelib_test_tray_exe_DLLS= odbc32 \
			ole32 \
			oleaut32 \
			winspool \
			odbccp32
winelib_test_tray_exe_LIBRARY_PATH=
winelib_test_tray_exe_LIBRARIES= uuid

winelib_test_tray_exe_OBJS= $(winelib_test_tray_exe_C_SRCS:.c=.o) \
			$(winelib_test_tray_exe_CXX_SRCS:.cpp=.o) \
			$(winelib_test_tray_exe_RC_SRCS:.rc=.res)



### Global source lists

C_SRCS                = $(winelib_test_tray_exe_C_SRCS)
CXX_SRCS              = $(winelib_test_tray_exe_CXX_SRCS)
RC_SRCS               = $(winelib_test_tray_exe_RC_SRCS)


### Tools

CC = winegcc
CXX = wineg++
RC = wrc
AR = ar


### Generic targets

all: $(SUBDIRS) $(DLLS:%=%.so) $(LIBS) $(EXES)

### Build rules

.PHONY: all clean dummy

$(SUBDIRS): dummy
	@cd $@ && $(MAKE)

# Implicit rules

.SUFFIXES: .cpp .cxx .rc .res
DEFINCL = $(INCLUDE_PATH) $(DEFINES) $(OPTIONS)

.c.o:
	$(CC) -c $(CFLAGS) $(CEXTRA) $(DEFINCL) -o $@ $<

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(CXXEXTRA) $(DEFINCL) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(CXXEXTRA) $(DEFINCL) -o $@ $<

.rc.res:
	$(RC) $(RCFLAGS) $(RCEXTRA) $(DEFINCL) -fo$@ $<

# Rules for cleaning

CLEAN_FILES     = y.tab.c y.tab.h lex.yy.c core *.orig *.rej \
                  \\\#*\\\# *~ *% .\\\#*

clean:: $(SUBDIRS:%=%/__clean__) $(EXTRASUBDIRS:%=%/__clean__)
	$(RM) $(CLEAN_FILES) $(RC_SRCS:.rc=.res) $(C_SRCS:.c=.o) $(CXX_SRCS:.cpp=.o)
	$(RM) $(DLLS:%=%.so) $(LIBS) $(EXES) $(EXES:%=%.so)

$(SUBDIRS:%=%/__clean__): dummy
	cd `dirname $@` && $(MAKE) clean

$(EXTRASUBDIRS:%=%/__clean__): dummy
	-cd `dirname $@` && $(RM) $(CLEAN_FILES)

### Target specific build rules
DEFLIB = $(LIBRARY_PATH) $(LIBRARIES) $(DLL_PATH) $(DLL_IMPORTS:%=-l%)

$(winelib_test_tray_exe_MODULE): $(winelib_test_tray_exe_OBJS)
	$(CC) $(winelib_test_tray_exe_LDFLAGS) -o $@ $(winelib_test_tray_exe_OBJS) $(winelib_test_tray_exe_LIBRARY_PATH) $(winelib_test_tray_exe_DLL_PATH) $(DEFLIB) $(winelib_test_tray_exe_DLLS:%=-l%) $(winelib_test_tray_exe_LIBRARIES:%=-l%)


